name: drawerapp
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: "^0.0.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/pic1.jpg
    - assets/pic2.jpg
    - assets/pic3.jpg
    - assets/pic4.jpg
    - assets/pic5.jpg
    - assets/pic6.jpg
